blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url:  https://github.com/newrelic/newrelic-java-agent/blob/master/README.md#support
    about: check out the README for troubleshooting directions
