name: GH Pages Cleanup

on:

  #Scheduled to run every Friday
  schedule:
    - cron: "0 8 * * 5"

jobs:
  cleanup:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout GH Pages
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: 'gh-pages'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@users.noreply.github.com"

      #Look in spotbugs and test reports for directories containing a date.txt file.
      #If the date.txt file contains a UTC string older than
      #five days ago, delete the directory.
      - name: Delete old spotbugs folders
        run: |
          cd gh-pages
          directories=$(find spotbugs -name date.txt -exec dirname {} \;)
          for directory in $directories; do
            date_in_file_utc=$(cat "$directory/date.txt")
            five_days_ago_utc=$(date -u -d "5 days ago" +%s)
            if ((date_in_file_utc < five_days_ago_utc)); then
              rm -rf $directory
            fi
          done

      - name: Delete old reports folders
        run: |
          cd gh-pages
          directories=$(find reports -name date.txt -exec dirname {} \;)
          for directory in $directories; do
            date_in_file_utc=$(cat "$directory/date.txt")
            five_days_ago_utc=$(date -u -d "5 days ago" +%s)
            if ((date_in_file_utc < five_days_ago_utc)); then
              rm -rf $directory
            fi
          done

      - name: Commit and push
        run: |
          cd gh-pages
          git add .
          git commit -m "Removing old folders from spotbugs and test reports"
          git push
