name: Branch Build - Java Instrumentation Tests

on:
  push:
    branches-ignore:
      - '**WIP**'

jobs:
  java-instrumentation-tests:
    uses: newrelic/newrelic-java-agent/.github/workflows/run-gradle-build.yml@tcrone/gha-build-adjustments
    with:
      command: ./gradlew --console=plain :instrumentation:test -Ptest8 -PnoScala --continue
